# Generated by Django 5.2.5 on 2025-11-21 08:19

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ghfdb", "0001_initial"),
        ("heat_flow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GHFDB",
            fields=[],
            options={
                "verbose_name": "Global Heat Flow Database",
                "verbose_name_plural": "Global Heat Flow Database",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("heat_flow.heatflow",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
